### ISSUE TITLE
Sending reports to existing launches results in error

### ISSUE THREAD

**Issue by gupta-kartik** [reportportal/client-net#122]
I think there might be a bug in the .net client when trying to write to the same launch.

According to the docs [here](https://github.com/reportportal/commons-net/blob/develop/docs/Configuration.md#reporting-experience), supplying the `uuid` of an existing launch to StartLaunchRequest should allow us to continue writing to the same launch:

```
var request = new StartLaunchRequest
                {
                    Name = launchName,
                    StartTime = DateTime.UtcNow,
                    Attributes = attributes,
                    Uuid = LaunchId
                };
```

The response however from Report Portal is:

```
--Inner Exception--
Response status code does not indicate success.
 InternalServerError (500) POST https://<reportportalinstance>/api/v1/<project>/launch
 {"errorCode":5000,"message":"Unclassified error [org.hibernate.exception.ConstraintViolationException: could not execute statement]"}
ReportPortal.Client.ServiceException
   at ReportPortal.Client.Resources.ServiceBaseResource.CheckSuccessStatusCode(HttpResponseMessage response, Stream stream)
   at ReportPortal.Client.Resources.ServiceBaseResource.SendHttpRequestAsync[TResponse](HttpMethod httpMethod, String uri, HttpContent httpContent, CancellationToken cancellationToken)
   at ReportPortal.Client.Resources.ServiceBaseResource.SendAsJsonAsync[TResponse,TRequest](HttpMethod httpMethod, String uri, TRequest request, CancellationToken cancellationToken)
   at ReportPortal.Client.Resources.ServiceLaunchResource.StartAsync(StartLaunchRequest request, CancellationToken cancellationToken)
````

We are using version 3.4.1 on ReportPortal.Shared.

**Comment by nvborisenko** [comment]
This is definitely server-side issue.
